security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\SecurityAuthenticator
            logout:
                path: /logout
            login_link:
                check_route: login_check
                max_uses: 100
                signature_properties: ['id', 'email']
                success_handler: App\Security\Handler\Confirmation\ConfirmationSuccessHandler


    access_control:
         - { path: ^/login$, roles: PUBLIC_ACCESS }
         - { path: ^/profile, roles: IS_AUTHENTICATED_FULLY }
         - { path: ^/timeline, roles: ROLE_ADMIN }
         - { path: ^/, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
